### ISSUE TITLE
shorten property names

### ISSUE THREAD

**Issue by FlorianZipser** [korpling/pepperModules-RelANNISModules#5]
I would propose to shorten the names for the new relANNIS4 Modul, since the long names aren't necessary any more with new pepper workflow configuration. And the user eventually has to type in those names.

Just remove the following:
public static final String PREFIX = "relANNIS.exporter.";

**Comment by thomaskrause** [comment]
This is fixed in the new ANNISModules exporter (https://github.com/korpling/pepperModules-ANNISModules)
